---
apiVersion: v1
kind: Namespace
metadata:
  name: staging-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-2
  namespace: staging-2
spec:
  selector:
    matchLabels:
      app: echoserver-2
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver-2
    spec:
      containers:
      - image: k8s.gcr.io/e2e-test-images/echoserver:2.5
        name: echoserver-2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-2
  namespace: staging-2
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: echoserver
